name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Landing Page
        run: npm install && npm run build

      - name: Build Toast
        run: cd projects/toast && npm install && npm run build

      - name: Build Material Cards
        run: cd projects/material-cards && npm install && npm run build

      - name: Build Stripe Canvas
        run: cd projects/stripe-canvas && npm install && npm run build

      - name: Build Neumorphism Soft UI Buttons
        run: cd projects/neumorphism-soft-ui-buttons && npm install && npm run build

      - name: Build Waves
        run: cd projects/waves && npm install && npm run build

      - name: Build Accordion
        run: cd projects/accordion && npm install && npm run build

      - name: Build Password Generator
        run: cd projects/secure-password-generator && npm install && npm run build

      - name: Build Auto hide Navigation Toolbar
        run: cd projects/auto-hide-navigation-toolbar && npm install && npm run build

      - name: Build Patterns
        run: cd projects/generative-art-patterns && npm install && npm run build

      - name: Build Flowers
        run: cd projects/generative-art-flowers && npm install && npm run build

      - name: Build Wrap
        run: cd projects/wrap-canvas && npm install && npm run build

      - name: Build Noise
        run: cd projects/noise && npm install && npm run build

      - name: Build Mandelbrot Set
        run: cd projects/mandelbrot-set && npm install && npm run build

      - name: Build Ants
        run: cd projects/generative-art-ants && npm install && npm run build

      - name: Prepare Files for Firebase Deploy
        run: node prepareFirebaseHosting.js

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          projectId: fir-git-dep
