name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Landing Page
        run: npm update && npm run build

      - name: Build Toast
        run: cd toast && npm update && npm run build

      - name: Build Material Cards
        run: cd material-cards && npm update && npm run build

      - name: Build Canvas
        run: cd canvas && npm update && npm run build

      - name: Build Neumorphism Soft UI Buttons
        run: cd neumorphism-soft-ui-buttons && npm update && npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          projectId: fir-git-dep
